options:
	color: <##B4C788>
	prefix: &8[<##B4C788>&lUMORIA&8]&f
	permission: &7Insufficient Permissions
	admin: &8[<##B4C788>&lADMIN&8]&7
	world: world

on load:
	execute console command "/mv unload survdupe_the_end"
	execute console command "/mv unload dupemp3"
	execute console command "/mv unload Xethyr"
	execute console command "/mv unload dupemp3_the_end"
	execute console command "/mv unload Ambarina"
	execute console command "/mv unload Rykene"
	execute console command "/mv unload world_the_end"
	execute console command "/mv unload world"
	execute console command "/mv unload survdupe"
	execute console command "/mv unload dupemp3_the_nether"
	execute console command "/mv unload voidworld"
	execute console command "/mv unload build_the_end"
	execute console command "/mv unload world_nether"
	execute console command "/mv unload Skyland"
	execute console command "/mv unload islands"
	execute console command "/mv unload world"
	execute console command "/mv unload piratehub_nether"