options:
	token: Nzc5MTExNDQ5MzQzMTY0NDE4.X7byFA.hIo0NDj7aUo-F85ZmnbbPeFdhH0
	charging: &8[<##BBEFE0>&lCHARGING&8]&7
	discord: &8[<##BBEFE0>&lDISCORD&8]&7
	permission: &7Insufficient Permissions
	admin: &8[<##BBEFE0>&lADMIN&8]&7
	world: world

on load:
	login to "{@token}" with the name "Charging"

discord command list:
	prefixes: "."
	executable in: guild
	trigger:
		set {_} to a message builder
		append line "```Online: %size of all players% - %all players%```"
		reply with {_}

discord command tps:
	prefixes: "."
	executable in: guild
	trigger:
		set {_} to a message builder
		append line "```TPS: %tps%```"
		reply with {_}

command /login:
	trigger:
		if player is op:
			login to "{@token}" with the name "Charging"
			send "{@admin} &7Logged In"
		else:
			send "{@admin} {@permission}"

command /logout:
	trigger:
		if player is op:
			logout of "Charging"
			send "{@admin} &7Logged Out"
		else:
			send "{@admin} {@permission}"

command /unlink [<player>]:
	trigger:
		if player is op:
			loop {discord::*}:
				if {discord::%loop-index%} is name of arg-1:
					delete {discord::%loop-index%}
					send "{@admin} &7Unlinked &7%arg-1%"
					stop
			send "{@admin} <##BBEFE0>%arg-1% &7is not linked"
		else:
			send "{@admin} {@permission}"

command /discord:
	trigger:
		send " "
		send "  {@discord}"
		send " "
		send "  <tooltip:<##BBEFE0>Click to join!><link:https://discord.gg/y333BGhxFP>&7Click Here to Join!<reset>"
		send " "

every 10 minutes:
	loop all players:
		send " " to loop-player
		send "  {@discord}" to loop-player
		send " " to loop-player
		send "  &7Join our <##BBEFE0>/discord &7for events, updates, and extra features" to loop-player
		send "  &7Link your account (<##BBEFE0>/link&7) to recieve perks! <tooltip:<##BBEFE0>Click to join!><link:https://discord.gg/y333BGhxFP>&8[<##BBEFE0>&lCLICK HERE&8]<reset>" to loop-player
		send " " to loop-player

command /link:
	trigger:
		if {discord::*} contains name of player:
			send "{@discord} &7Discord already linked"
			stop
		set {_code} to a random integer between 11111 and 99999
		set {code::%{_code}%} to name of player
		set {_copy} to new text component of "  <##BBEFE0>Click here &7to copy command to clipboard. "
		set click event of {_copy} to a new click event to copy ".link %{_code}%" to clipboard
		set hover event of {_copy} to a new hover event showing "<##BBEFE0>Copy to Clipboard"
		send " "
		send "  {@discord}"
		send " "
		send "  &7Run the command <##BBEFE0>.link %{_code}% &7in <##BBEFE0>##link &7to link your account"
		send "  <##BBEFE0>Rewards: &710b coins and 10a wrath  &8|  &7Valid for <##BBEFE0>1 &7minute"
		send components {_copy} to player
		send " " 
		wait 1 minute
		delete {code::%{_code}%}

discord command link [<text>]:
	prefixes: "."
	trigger:
		if the name of the channel is not "link":
			delete discord entity event-message
			stop
		if arg-1 is not set:
			reply with "```.link <code>```"
			delete discord entity event-message
			stop
		if {code::%arg-1%} is not set:
			reply with "```Invalid code```"
			delete discord entity event-message
			stop
		set {discord::%discord id of event-member%} to {code::%arg-1%}
		reply with "```Sucessfully Linked with %{code::%arg-1%}%. Rewards have been added to your account. ```"
		add 10000000 to {p_coins::%{code::%arg-1%}%}
		add 10000000 to {p_totalcoins::%{code::%arg-1%}%}
		add 10000 to {p_wrath::%{code::%arg-1%}%}
		add 10000 to {p_totalwrath::%{code::%arg-1%}%}
		send "```Link: %discord id of event-member%, %{code::%arg-1%}%```" to channel with id "886738161491914772" with "Charging"
		delete {code::%arg-1%}

discord command top [<text>]:
	prefixes: "."
	executable in: guild
	trigger:
		set {_} to a message builder
		if arg-1 is not "level" or "coins" or "totalcoins" or "wrath" or "totalwrath" or "totalstigma" or "pkill" or "mkill" or "rebirth" or "maxhealth" or "damage":
			append line "```.top <level coins totalcoins wrath totalwrath totalstigma pkill mkill rebirth>```"
			reply with {_}
		else:
			loop {p_%arg-1%::*}:
				add 1 to {_size}
				if {_low.to.high.list::%loop-value%} is not set:
					set {_low.to.high.list::%loop-value%} to loop-index
				else:
					set {_n} to 0
					loop {_size} times:
						set {_n} to {_n}+1
						{_low.to.high.list::%loop-value-1%.%{_n}%} is not set
						set {_low.to.high.list::%loop-value-1%.%{_n}%} to loop-index
						stop loop
			wait 1 tick
			set {_n} to size of {_low.to.high.list::*}
			loop {_low.to.high.list::*}:
				set {_high.to.low.list::%{_n}%} to loop-value
				set {_n} to {_n}-1
			wait 1 tick
			set {_i} to 0
			append line "```----------- [ TOP ] -------------"
			loop {_high.to.low.list::*}:
				if arg-1 is "level":
					set {_label} to ":L%{p_%arg-1%::%loop-value%}%"
				else if arg-1 is "coins" or "totalcoins":
					set {_coins} to format({p_%arg-1%::%loop-value%})
					set {_label} to "%{_coins}% coins"
				else if arg-1 is "wrath" or "totalwrath":
					set {_wrath} to format({p_%arg-1%::%loop-value%})
					set {_label} to "%{_wrath}% wrath"
				else if arg-1 is "totalstigma":
					set {_stigma} to format({p_%arg-1%::%loop-value%})
					set {_label} to "%{_stigma}% stigma"
				else if arg-1 is "mkill" or "pkill":
					set {_label} to "%{p_%arg-1%::%loop-value%}% kills"
				else if arg-1 is "rebirth":
					set {_label} to "%{p_%arg-1%::%loop-value%}% times"
				else if arg-1 is "maxhealth":
					set {_label} to "%{%arg-1%::%loop-value%}% ❤"
				else if arg-1 is "damage":
					set {_label} to "%{%arg-1%::%loop-value%}% dmg"
				add 1 to {_topnumber}
				set {_player} to "%loop-value%" parsed as offline player
				append line "%{_topnumber}%. %{_player}% : %{_label}%"
				add 1 to {_i}
				if {_topnumber} > 10:
					stop
			append line "```"
			reply with {_}